# Generated by Django 4.2.4 on 2023-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [ ]

    operations = [
        migrations.CreateModel(
            name='CrhpExportData',
            fields=[
                ('resourceinstanceid', models.UUIDField(primary_key=True, serialize=False)),
                ('site_descriptors', models.JSONField()),
                ('borden_number', models.CharField()),
                ('defining_elements', models.CharField()),
                ('physical_description', models.CharField()),
                ('document_location', models.CharField()),
                ('heritage_value', models.CharField()),
                ('street_address', models.CharField()),
                ('city', models.CharField()),
                ('locality', models.CharField()),
                ('location_description', models.CharField()),
                ('site_boundary', models.IntegerField()),
                ('boundary_geojson', models.CharField()),
                ('area_sqm', models.DecimalField(decimal_places=5, max_digits=12)),
                ('ownership', models.CharField()),
                ('heritage_category', models.CharField()),
                ('contributing_resource_count', models.IntegerField()),
                ('functional_category', models.CharField()),
                ('functional_state', models.JSONField()),
                ('heritage_themes', models.JSONField()),
                ('registration_status', models.CharField()),
                ('registry_types', models.JSONField()),
                ('officially_recognized_site', models.BooleanField()),
                ('authority', models.CharField()),
                ('legal_instrument', models.CharField()),
                ('act_section', models.CharField()),
                ('recognition_type', models.CharField()),
                ('responsible_government_name', models.CharField()),
                ('reference_number', models.CharField()),
                ('designation_or_protection_start_date', models.DateField()),
                ('site_images', models.JSONField()),
                ('external_url_type', models.CharField()),
                ('external_url', models.JSONField()),
            ],
            options={
                'db_table': '',
                'managed': False,
            },
        ),
    ]
