# Generated by Django 4.2.4 on 2023-11-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="crhpexportdata",
            table="bcrhp_crhp_data_vw",
        ),
    ]
