# Generated by Django 4.2.13 on 2024-06-18 10:11

from django.db import migrations
from bcrhp.migrations.operations.privileged_sql import RunPrivilegedSQL

class Migration(migrations.Migration):

    dependencies = [
        ('bcrhp', '0004_historic_site_one_line'),
    ]

    operations = [
        RunPrivilegedSQL(
            """
            begin;
            delete from map_layers ml
            using (
                select distinct ml.maplayerid
                from map_layers ml,
                lateral jsonb_array_elements(ml.layerdefinitions) AS elm
                where elm->>'source' IN (
                    'natural-resource-regions-source-Natural Resource Regions',
                    'nts250k-source-NTS 1:250k',
                    'nts50k-source-NTS 1:50k',
                    'provinces-states-source-Provinces and States',
                    'trim-contours-source-TRIM Contours'
                )
            ) subquery
            where ml.maplayerid = subquery.maplayerid
            ;

            delete from map_sources
            where name in (
                'natural-resource-regions-source-Natural Resource Regions'
                , 'nts250k-source-NTS 1:250k'
                , 'nts50k-source-NTS 1:50k'
                , 'provinces-states-source-Provinces and States'
                , 'trim-contours-source-TRIM Contours'
            )
            ;
            commit;
            """,
            # TODO FIXME: replace /bcrhp/ with /int/bcrhp/
            """
            begin;
            insert into map_layers (maplayerid, name, layerdefinitions, isoverlay, icon, activated, addtomap, centerx, centery, zoom, legend, searchonly, sortorder, ispublic)
            values
                ('58928bf0-3bc9-4e73-8d32-f099ddcb5187', 'Provinces and States', '[{"id": "provinces-states", "type": "line", "paint": {"line-color": "rgba(102,136,102,1)", "line-width": 2, "line-dasharray": [8, 4, 4, 4]}, "source": "provinces-states-source-Provinces and States", "source-layer": "WHSE_BASEMAPPING.DBM_BC_7H_MIL_POLITICAL_POLY"}]', 'true', 'fa fa-globe', 'true', 'false', NULL, NULL, NULL, '<p><img alt="" class="province-state legend-line" style="width: 8px;" src="/int/bcrhp/static/img/blank.png" /><img alt="" class="cadastral legend-line" src="/int/bcrhp/static/img/blank.png" />Province/State Boundary</p>', 'false', '0', 'true')
                , ('2d98a2e2-2eae-466d-bc29-cccbc405d766', 'NTS 1:50k', '[{"id": "nts50k-vector", "type": "line", "paint": {"line-color": "rgba(152, 152, 152, 1)"}, "source": "nts50k-source-NTS 1:50k", "minzoom": 6, "source-layer": "WHSE_BASEMAPPING.NTS_50K_GRID"}, {"id": "nts50k-symbol", "type": "symbol", "paint": {"text-color": "rgba(52, 52, 52, 1)"}, "layout": {"text-font": ["Open Sans Italic", "Arial Unicode MS Regular"], "text-size": 11, "text-field": "{MAP_TILE_DISPLAY_NAME}"}, "source": "nts50k-source-NTS 1:50k", "minzoom": 6, "source-layer": "WHSE_BASEMAPPING.NTS_50K_GRID"}]', 'true', 'fa fa-globe', 'true', 'false', NULL, NULL, NULL, '<p><img alt="" class="nts50 legend-line" src="/int/bcrhp/static/img/blank.png" />National Topographic System 1:50k Grid</p>', 'false', '0', 'false')
                , ('90f99529-9114-4bc8-8ec1-792574fcd34a', 'NTS 1:250k', '[{"id": "nts250k-vector", "type": "line", "paint": {"line-color": "rgb(52, 52, 52)"}, "source": "nts250k-source-NTS 1:250k", "source-layer": "WHSE_BASEMAPPING.NTS_250K_GRID"}, {"id": "nts250k-symbol", "type": "symbol", "paint": {"text-color": "rgb(52, 52, 52)"}, "layout": {"text-font": ["Open Sans Italic", "Arial Unicode MS Regular"], "text-size": 14, "text-field": "{MAP_TILE_DISPLAY_NAME}"}, "source": "nts250k-source-NTS 1:250k", "source-layer": "WHSE_BASEMAPPING.NTS_250K_GRID"}]', 'true', 'fa fa-globe', 'true', 'false', NULL, NULL, NULL, '<p><img alt="" class="nts250 legend-line" src="/int/bcrhp/static/img/blank.png" />National Topographic System 1:250k Grid</p>', 'false', '0', 'false')
                , ('f54b54b7-2619-48c9-be10-c6f2e70e53b2', 'Natural Resource Regions', '[{"id": "natural-resource-regions", "type": "line", "source": "natural-resource-regions-source-Natural Resource Regions", "source-layer": "WHSE_ADMIN_BOUNDARIES.ADM_NR_REGIONS_SPG"}, {"id": "natural-resource-regions-symbol", "type": "symbol", "paint": {"text-color": "#333333"}, "layout": {"text-field": "{REGION_NAME}"}, "source": "natural-resource-regions-source-Natural Resource Regions", "source-layer": "WHSE_ADMIN_BOUNDARIES.ADM_NR_REGIONS_SPG"}]', 'true', 'fa fa-globe', 'true', 'false', NULL, NULL, NULL, NULL, 'false', '0', 'true')
                , ('d2bfdebd-377f-4906-a161-ae24ed60628a', 'TRIM Contours', '[{"id": "trim-contours", "type": "line", "paint": {"line-color": ["case", ["==", ["%", ["to-number", ["get", "ELEVATION"]], 100], 0], "rgb(130, 130, 130)", "rgba(178,178,178,1)"], "line-width": ["case", ["==", ["%", ["to-number", ["get", "ELEVATION"]], 100], 0], 0.3, 0.25]}, "source": "trim-contours-source-TRIM Contours", "maxzoom": 20, "minzoom": 3, "source-layer": "WHSE_BASEMAPPING.TRIM_CONTOUR_LINES"}]', 'true', 'fa fa-globe', 'true', 'false', NULL, NULL, NULL, '<p><img alt="" class="legend-line trim-contours-20" src="/int/bcrhp/static/img/blank.png" />20m contours<br /><img alt="" class="legend-line trim-contours-100" src="/int/bcrhp/static/img/blank.png" />100m contours</p>', 'false', '0', 'false')
            ;

            insert into map_sources (id, name, source)
            values
                (11, 'natural-resource-regions-source-Natural Resource Regions', '{"type": "vector", "tiles": ["/bcrhp/bctileserver/geo/pub/WHSE_ADMIN_BOUNDARIES.ADM_NR_REGIONS_SPG/ows?service=WMS&request=GetMap&layers=WHSE_ADMIN_BOUNDARIES.ADM_NR_REGIONS_SPG&styles=&format=pbf&transparent=true&version=1.1.1&height=512&width=512&srs=EPSG:3857&bbox={bbox-epsg-3857}"], "tileSize": 512}')
                , (13, 'nts250k-source-NTS 1:250k', '{"type": "vector", "tiles": ["/bcrhp/bctileserver/geo/pub/WHSE_BASEMAPPING.NTS_250K_GRID/ows?service=WMS&request=GetMap&layers=WHSE_BASEMAPPING.NTS_250K_GRID&styles=&format=pbf&transparent=true&version=1.3.0&height=512&width=512&srs=EPSG:3857&bbox={bbox-epsg-3857}"], "tileSize": 512}')
                , (14, 'provinces-states-source-Provinces and States', '{"type": "vector", "tiles": ["/bcrhp/bctileserver/geo/pub/WHSE_BASEMAPPING.DBM_BC_7H_MIL_POLITICAL_POLY/ows?format=pbf&service=WMS&version=1.3.0&request=GetMap&srs=EPSG:3857&width=512&height=512&transparent=true&layers=pub:WHSE_BASEMAPPING.DBM_BC_7H_MIL_POLITICAL_POLY&bbox={bbox-epsg-3857}"], "tileSize": 512}')
                , (23, 'nts50k-source-NTS 1:50k', '{"type": "vector", "tiles": ["/bcrhp/bctileserver/geo/pub/WHSE_BASEMAPPING.NTS_50K_GRID/ows?service=WMS&request=GetMap&layers=WHSE_BASEMAPPING.NTS_50K_GRID&styles=&format=pbf&transparent=true&version=1.3.0&height=512&width=512&srs=EPSG:3857&bbox={bbox-epsg-3857}"], "tileSize": 512}')
                , (27, 'trim-contours-source-TRIM Contours', '{"type": "vector", "tiles": ["/bcrhp/bctileserver/geo/pub/WHSE_BASEMAPPING.TRIM_CONTOUR_LINES/ows?service=WMS&request=GetMap&layers=WHSE_BASEMAPPING.TRIM_CONTOUR_LINES&styles=&format=pbf&transparent=true&version=1.3.0&height=512&width=512&srs=EPSG:3857&bbox={bbox-epsg-3857}"], "tileSize": 512}')
            ;
            commit;
            """,
        )
    ]
