# Generated by Django 4.2.13 on 2024-06-24 11:16

from django.core.management import call_command
from django.db import migrations
from django.db.migrations.operations.special import RunPython

from bcrhp.settings import APP_ROOT

mapbox_overlays_dir = f'{APP_ROOT}/pkg/map_layers/mapbox_spec_json/overlays'

MapEntry = namedtuple('MapEntry', 'name file')
map_layers = [
    MapEntry('Borden Grid', 'borden-grid'),
    MapEntry('Cadastral ParcelMap', 'cadastral'),
    MapEntry('Crown Tenures', 'crown-tenures'),
    MapEntry('', ''),
]

def forward(apps, schema_editor):
    for ml in map_layers:
        call_command('packages', operation='delete_mapbox_layer', layer_name=ml.name)
        call_command('packages', operation='add_mapbox_layer',
                     layer_name=ml.name,
                     mapbox_json_path=f'{mapbox_overlays_dir}/{ml.file}/{ml.file}.json')


def backward(apps, schema_editor):
    MapLayer = apps.get_model('arches', 'MapLayer')
    for ml in map_layers:
        update = MapLayer(name=ml.name)
        update.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bcrhp', '0007_add_map_layers_665'),
    ]

    operations = [
        RunPython(forward, backward)
    ]
