# Generated by Django 4.2.13 on 2024-06-24 11:16
from django.db import migrations

from bcgov_arches_common.migrations.operations.privileged_sql import RunPrivilegedSQL


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "665_3_add_map_layers"),
    ]

    operations = [
        RunPrivilegedSQL(
            """
            update map_layers set ispublic=true where name in ('Borden Grid', 'Cadastral ParcelMap', 'Rivers', 'Streams');
            update map_layers set ispublic=false where name = 'Crown Tenures';
            """,
            """
            update map_layers set ispublic=true where name in ('Borden Grid', 'Cadastral ParcelMap', 'Crown Tenures');
            update map_layers set ispublic=false where name in ('Rivers', 'Streams');
            """,
        )
    ]
