# Generated by Django 4.2.13 on 2024-06-18 10:12

from django.core.management import call_command
from django.db import migrations
from django.db.migrations.operations.special import RunPython

from bcrhp.settings import APP_ROOT

mapbox_overlays_dir = f"{APP_ROOT}/pkg/map_layers/mapbox_spec_json/overlays"


def forward(apps, schema_editor):
    call_command(
        "packages",
        operation="add_mapbox_layer",
        layer_name="Indigenous Reserves and Band Names",
        mapbox_json_path=f"{mapbox_overlays_dir}/indian-reserves-band-names/indian-reserves-band-names.json",
    )
    call_command(
        "packages",
        operation="delete_mapbox_layer",
        layer_name="Indigenous Reserve Boundaries",
    )


def backward(apps, schema_editor):
    call_command(
        "packages",
        operation="add_mapbox_layer",
        layer_name="Indigenous Reserve Boundaries",
        mapbox_json_path=f"{mapbox_overlays_dir}/indigenous-reserve-admin-boundaries/indigenous-reserve-admin-boundaries.json",
    )
    call_command(
        "packages",
        operation="delete_mapbox_layer",
        layer_name="Indigenous Reserves and Band Names",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "665_1_remove_map_layers"),
    ]

    operations = [RunPython(forward, backward)]
