# Generated by Django 4.2.13 on 2024-06-18 11:16

from django.db import migrations
from bcgov_arches_common.migrations.operations.privileged_sql import RunPrivilegedSQL


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "665_4_public_internal_map_layers"),
    ]

    operations = [
        RunPrivilegedSQL(
            """
            begin;
            update map_layers set sortorder = 1 where name = 'Cadastral ParcelMap';
            update map_layers set sortorder = 2 where name = 'Municipal Boundaries';
            update map_layers set sortorder = 3 where name = 'Regional District Boundaries';
            update map_layers set sortorder = 4 where name = 'Indian Reserves and Band Names';
            update map_layers set sortorder = 5 where name = 'Islands Trust Administrative Boundaries Outlined';
            update map_layers set sortorder = 6 where name = 'Local Trust Administrative Boundaries';
            update map_layers set sortorder = 7 where name = 'Tourism Regions';
            update map_layers set sortorder = 8 where name = 'Digital Roads Atlas';
            update map_layers set sortorder = 9 where name = 'TRIM Water Lines';
            update map_layers set sortorder = 10 where name = 'Lakes';
            update map_layers set sortorder = 11 where name = 'Rivers';
            update map_layers set sortorder = 12 where name = 'Streams';
            update map_layers set sortorder = 13 where name = 'Crown Tenures';
            update map_layers set sortorder = 14 where name = 'Tantalis Surveyed Parcel';
            update map_layers set sortorder = 15 where name = 'Parks - National';
            update map_layers set sortorder = 16 where name = 'Parks - Provincial';
            update map_layers set sortorder = 17 where name = 'Parks - Municipal';
            update map_layers set sortorder = 18 where name = 'Borden Grid';
            update map_layers set sortorder = 19 where name = 'Heritage Sites';
            commit;
            """,
            """
            update map_layers set sortorder = 0;
            """,
        )
    ]
