# Generated by Django 4.2.13 on 2024-07-09 12:55
from django.db import migrations
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "983_delete_addresses"),
    ]

    operations = [
        RunSQL(
            """
            begin;
            update map_layers set ispublic=true where name in (
                'Borden Grid'
                , 'Cadastral ParcelMap'
                , 'Digital Roads Atlas'
                , 'Lakes'
                , 'Municipal Boundaries'
                , 'Parks - Provincial'
                , 'Parks - Municipal'
                , 'Parks - National'
                , 'Regional District Boundaries'
                , 'Rivers'
                , 'Streams'
                , 'TRIM Water Lines'
            );
            update map_layers set ispublic=false where name in (
                'Crown Tenures'
                , 'Indigenous Reserves and Band Names'
                , 'Islands Trust Administrative Boundaries Outlined'
                , 'Local Trust Administrative Boundaries'
                , 'Tantalis Surveyed Parcel'
                , 'Tourism Regions'
            );
            commit;
            """,
            """
            begin;
            update map_layers set ispublic=true where name in (
                'Borden Grid'
                , 'Cadastral ParcelMap'
                , 'Crown Tenures'
                , 'Indigenous Reserves and Band Names'
            );
            update map_layers set ispublic=false where name in (
                'Digital Roads Atlas'
                , 'Lakes'
                , 'Municipal Boundaries'
                , 'Parks - Provincial'
                , 'Parks - Municipal'
                , 'Parks - National'
                , 'Regional District Boundaries'
                , 'Rivers'
                , 'Streams'
                , 'TRIM Water Lines'
            );
            commit;
            """,
        )
    ]
