name: bcrhp7-6
services:
  bcrhp:
    container_name:  bcrhp7-6
    image: bcgov/bcrhp7-6
    build:
      context: ..
      dockerfile: bcrhp/Dockerfile
    command: run_arches
    volumes:
      - ../arches/:/web_root/arches
      - ./:/web_root/bcrhp
      - ../arches_common/:/web_root/arches_common
    env_file:
      - ./docker/env_file.env
    ports:
      - 8025:8000
      - 5688:5678
      - 80:80
      - 443:443
    stdin_open: true
    tty: true

  bcrhp-webpack:
    container_name: bcrhp-webpack7-6
    image: bcgov/bcrhp-webpack7-6
    build:
      context: ..
      dockerfile: bcrhp/docker/webpack/Dockerfile
    command: run_webpack
    volumes:
      - ../arches/:/web_root/arches
      - ./:/web_root/bcrhp
    env_file:
      - ./docker/webpack/env_file.env
    ports:
      - 8022:8021
    stdin_open: true
    tty: true

networks:
  default:
    external: true
    name: arches7-5-2-dev


volumes:
  arches-log-bcrhp7-6:
  arches-static-bcrhp7-6: